window.language_en_US = {
    'Sign in / up':'Sign in / up',
	"MenuChat": "Chat",
	"MenuVideoChat": "Video Chat",
	"PrincipalHeader": "Anyone Anywhere",
	"SecondHeader": "A free, premium quality, responsive one page Bootstrap theme created by Start Bootstrap.",
	"SignUp": "Sign up",
	"SignIn": "Sign in",
	"Email": "Email",
	"FormatIncorrect": "format is incorrect",
	"Username": "Username",
	"UsernameExists": "exist",
	"Password": "Password",
	"Or": "or",
	"Incorrect": "incorrect",
	"UsernameOrEmail": "Username or email",
	"ForgotPassword": "Forgot password",
	"EnterEmail": "Please enter your email.",
	"Success": "Success!",
	"EmailHasBeenSent": "an email has been send, please check your inbox",
	"Oops": "Oops!",
	"EmailDoesNotExist": "looks like that email does not exist on out servers.",
	"Send": "Send",
	"Test": "Test"
}