window.language_es_CO ={
    'You have':'Tiene',
    'Sign in / up':'Crear o iniciar',
	"MenuChat": "Chat",
    'Sign up':'Crear cuenta',
	"MenuVideoChat": "Video Chat",
	"PrincipalHeader": "Anyone Anywhere",
	"SignUp": "Sign up",
	"SignIn": "Sign in",
	"Email": "Email",
	"FormatIncorrect": "format is incorrect",
	"Username": "Nombre de usuario",
	"UsernameExists": "Usuario existe",
	"Password": "Contraseña",
	"Or": "o",
	"Incorrect": "Incorrecto",
	"Username or email": "Username or email",
	"ForgotPassword": "Forgot password",
	"EnterEmail": "Please enter your email.",
	"Success": "Success!",
	"EmailHasBeenSent": "an email has been send, please check your inbox",
	"Oops": "Oops!",
	"EmailDoesNotExist": "looks like that email does not exist on out servers.",
	"Send": "Send",
    'days left to confirm your account via email.':'dias para confirmar su correo',
    'here':'aqui',
    'to resend it to your email':'Para reenviar su correo',
    'Me':'Yo',
    'Email has been send':'Correo se envio exitosamente',
    'cancel video chat':'Cancelar video chat',
    'Anonym':'Anonimo',
    'looking for Bipers':'Buscando Bipers',
    'New room':'Nueva sala',
    'Change room':'Cambiar sala',
    'User Typing...':'Usuario esta digitando...',
    'My Profile':'Mi perfil',
    'Birthday':'Cumpleños',
    'Location':'Ubicacion',
    'Where are you?':'Donde estas?',
    'Would you like to share your location?':'Te gustaria compartir tu ubicacion?',
    'Gender':'Sexo',
    'About you':'Sobre ti',
    'Save':'Guardar',
    'If you want to delete your account, just click':'Si quieres borrar tu cuenta, solo haz click',
    'Name':'Nombre',
    'Birth':'Fecha de nacimiento',
    'Sorry :( this is an Anonym user and doesnt have info for us.':'Este usuario no tiene informacion que compartir',
    'Anonym info':'Informacion del anonimo',
    'Hi there!':'Hola!',
    'Welcome to mitbip! click':'Bienvenido a mitbip! Click',
    'to sign up or login, or just click':'para crear cuenta o iniciar sesion, or solo haz click',
    'if you wanna chat NOW!':'Si quieres chatiar ya!',
    'When you click in "chat" or "sign up / login" you are accepting':'Dando click en algunos de estos links, aceptas',
    'this':'Estos',
    'terms':'terminos',
    'Terms':'terminos',
    'Sorry, but we dont support video chat in this browser. You can go back to the text chat by clicking':'Tu navegador no soporta camara, puedes volver a chatiar haciendo click',
    'Sorry, looks like you dont have a camera or you are using a unsupported browser':'No tienes camara o estas usando un navegador desactualizado'
};