window.language_es_CO ={
  'You have':'Tiene',
  'Join us':'Únetenos',
  'Sign up':'Crear cuenta',
  "Password": "Contraseña",
  "Or": "o",
  "Incorrect": "Incorrecto",
  "Username or email": "Nombre de usuario o correo",
  "Success": "Exito!",
  "Oops": "Oops!",
  "Send": "Enviar",
  'days left to confirm your account via email.':'días restantes para confirmar tu cuenta, por medio de tu correo.',
  'here':'aquí',
  'to resend it.':'Para reenviarlo',
  'Me':'Yo',
  'Email has been sent':'El correo se envió exitosamente',
  'cancel video chat':'Cancelar video chat',
  'Anonym':'Anonimo',
  'Looking for Bipers':'Buscando Bipers',
  'New room':'Nueva sala',
  'Change room':'Cambiar sala',
  'User Typing...':'El usuario está digitando...',
  'My Profile':'Mi perfil',
  'Birthday':'Fecha de nacimiento',
  'Location':'Ubicación',
  'Where are you?':'Dónde estás?',
  'Would you like to share your location?':'Te gustaría compartir tu ubicación?',
  'Gender':'Sexo',
  'About you':'Sobre ti',
  'Save':'Guardar',
  'If you want to delete your account, just click':'Si quieres borrar tu cuenta, solo haz click',
  'Name':'Nombre',
  'Birth':'Fecha de nacimiento',
  "Sorry, this is an Anonym user and does not have info for us.":'Lo sentimos, este usuario es anónimo y no tiene información que compartir',
  'Anonym info':'Información del anonimo',
  'Hi there!':'Hola!',
  'Welcome to mitbip! click':'Bienvenido a mitbip! Click',
  'to sign up or login, or just click':'para crear cuenta o iniciar sesion, o solo haz click',
  'if you wanna chat NOW!':'Si quieres chatear YA!',
  'When you click in "chat" or "Join us" you are accepting':'Dando click en alguno de estos links, estás aceptando',
  'this':'estos',
  'terms':'términos',
  'Terms':'Términos',
  'Sorry, but we dont support video chat in this browser. You can go back to the text chat by clicking':'Lo sentimos, tu navegador no soporta cámara web, puedes volver a chatear haciendo click',
  'Sorry, looks like you dont have a camera or you are using a unsupported browser':'Lo sentimos, no tienes cámara web o estás usando un navegador desactualizado',
  'Sorry, we dont have permissions to control your camera': 'Lo sentimos, no tenemos permisos para ingresar a tu cámara'
};